The Runmons Reckoning
TwitchPlaysPokemon/pbr-movesets pull request #49
Opened 2021-03-24 18:24 UTC by red031000

Reopening PR #39

2021-03-24 18:24 UTC, red031000 commented
it appears that a conflict was introduced here due to the merge fuckery, if that could be resolved that'd be great

2021-04-22 18:06 UTC, MathyFurret requested changes
I think you fixed the error in some places but it's still in others (the compile script is silent about it and i sort of know why, but i dont know the semantics about duplicated keys in yaml)

2021-04-22 18:06 UTC, MathyFurret commented on pokesets/Runmon/12_PuppetPlay.yaml
> +
Missing --- between sets here too.

2021-04-22 18:06 UTC, MathyFurret commented on pokesets/Runmon/17_Brown.yaml
> +
Still need a --- here

2021-04-22 18:06 UTC, MathyFurret commented on pokesets/Runmon/47_Sirius.yaml
> +
--- here

2021-04-22 18:06 UTC, MathyFurret commented
Pinging @SolarisLumos ^^^ because i forgot he wont get notifs anymore

2021-04-23 16:00 UTC, merged

2021-04-23 16:00 UTC, MathyFurret commented
thank you so much! and sorry about all the delays